export const USER = [
    {
        id: "3fac26f9",
        username: "employee001",
        password: "password12345",
        role: "emp",
        birthday: "11/1/2000",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "711edaa3",
        username: "employee002",
        password: "password12345",
        role: "emp",
        birthday: "11/1/2001",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "41ed258a",
        username: "employee003",
        password: "password12345",
        role: "emp",
        birthday: "11/1/2001",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "aea4e58c",
        username: "manager001",
        password: "password12345",
        role: "man",
        birthday: "10/7/2000",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
];
