export const USER = [
    {
        id: "3fac26f9",
        username: "employee001",
        password: "password12345",
        role: "emp",
        birthday: "11/1/2000",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "711edaa3",
        username: "employee002",
        password: "password12345",
        role: "emp",
        birthday: "11/1/2001",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "41ed258a",
        username: "employee003",
        password: "password12345",
        role: "emp",
        birthday: "11/1/2001",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "aea4e58c",
        username: "manager001",
        password: "password12345",
        role: "man",
        birthday: "10/7/2000",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "aea4e58c1",
        username: "manager002",
        password: "1",
        role: "man",
        birthday: "10/7/2000",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "aea4e58c2",
        username: "employee004",
        password: "1",
        role: "man",
        birthday: "10/7/2000",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
    {
        id: "aea4e58c3",
        username: "hr",
        password: "1",
        role: "hr",
        birthday: "10/7/2000",
        sex: "M",
        bloodGroup: "O",
        address: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        tempAddress: "123, đường Võ Văn Kiệt, quận 2, TP. Hồ Chí Minh",
        numberInsurance: "39120938901839",
        numFax: "",
        numTechcombank: "191273821312898390128",
        numPassport: "",
        expricePassport: "",
        vehicleType: "Xe máy",
        vehicleId: "73-A1 99986",
        eduInfo: {
            school: "Trường Đại học FPT HCM",
            industry: "Logistic",
            graduationYear: "2020",
            degree: "",
            difficulDegree: "",
            JapaneseLicense: "",
            EnglishLicense: "",
        },
    },
];


export const SALARY = [
    {
        id: '96de3ad4',
        totalWorkingDays: 10,
        amount: 200,
        currencyUnit: 'USD',
        fromDate: '1/2/2021',
        toDate: '23/2/2021',
        createdDate: '12/2/2023',
        paidDate: '12/2/2023',
        status: 'Paid',
        ofEmployessId: '3fac26f9'
    },
    {
        id: '0667d557',
        totalWorkingDays: 13,
        amount: 260,
        currencyUnit: 'USD',
        fromDate: '1/2/2021',
        toDate: '23/2/2021',
        createdDate: '12/2/2023',
        paidDate: '12/2/2023',
        status: 'Paid',
        ofEmployessId: '3fac26f9'
    },
    {
        id: 'bc39',
        totalWorkingDays: 10,
        amount: 200,
        currencyUnit: 'USD',
        fromDate: '1/2/2021',
        toDate: '23/2/2021',
        createdDate: '12/2/2023',
        paidDate: '12/2/2023',
        status: 'Not yet',
        ofEmployessId: '3fac26f9'
    }, {
        id: '3f6a6f6e',
        totalWorkingDays: 15,
        amount: 300,
        currencyUnit: 'USD',
        fromDate: '1/2/2021',
        toDate: '23/2/2021',
        createdDate: '12/2/2023',
        paidDate: '12/2/2023',
        status: 'Paid',
        ofEmployessId: '711edaa3'
    }, {
        id: '8324',
        totalWorkingDays: 13,
        amount: 260,
        currencyUnit: 'USD',
        fromDate: '1/2/2021',
        toDate: '23/2/2021',
        createdDate: '12/2/2023',
        paidDate: '12/2/2023',
        status: 'Paid',
        ofEmployessId: '711edaa3'
    }, {
        id: '009ee780fc93',
        totalWorkingDays: 20,
        amount: 800,
        currencyUnit: 'USD',
        fromDate: '1/2/2021',
        toDate: '23/2/2021',
        createdDate: '12/2/2023',
        paidDate: '12/2/2023',
        status: 'Paid',
        ofEmployessId: 'aea4e58c'
    }, {
        id: 'fc91067e',
        totalWorkingDays: 21,
        amount: 840,
        currencyUnit: 'USD',
        fromDate: '1/2/2021',
        toDate: '23/2/2021',
        createdDate: '12/2/2023',
        paidDate: '12/2/2023',
        status: 'Paid',
        ofEmployessId: 'aea4e58c'
    },
]
